version: 2.1

orbs:
  orb-utils: circleci/orb-tools@volatile
workflows:
  btd:
    jobs:
      - orb-utils/pack-and-validate-orb:
          path: ./src/
          workspace-path: orb-packed/
          artifact-path: orb-packed/
          name: pack-and-validate
      - orb-utils/publish-dev-orb:
          namespace: circleci
          orb: hello-build
          label: ${CIRCLE_BRANCH}
          workspace-path: orb-packed/
          token-variable: "$CIRCLECI_API_TOKEN"
          requires: [pack-and-validate]







