version: 2.1

description: |
  A simple "Hello, World!" orb

executors:
  default:
    parameters:
      tag:
        type: string
        default: "curl-browsers"
    docker:
      - image:  circleci/buildpack-deps:<< parameters.tag >>

jobs:
  hello-build:
    executor: default
    steps:
      - hello-triggerer
      - circleci-env-highlights
      - system-info
