description: |
  A simple "Hello, World!" orb
display:
  source_url: https://github.com/circleci-public/hello-orb
executors:
  default:
    docker:
    - image: bash:4.4.19
jobs:
  hello-build:
    executor: default
    parameters:
      to:
        default: ${CIRCLE_USERNAME}
        type: string
    steps:
    - hello-triggerer:
        to: <<parameters.to>>
    - circleci-env-highlights
    - system-info
version: 2.1

